#Administrador#
admin: [ ROLE_ADMIN ]

#App Transporte#
transporte: [ ROLE_TRANSPORTE, ROLE_SOLICITANTE_TRANSPORTE, ROLE_ESPECIALISTA_TRANSPORTE, ROLE_SUPERVISOR_TRANSPORTE, ROLE_TECNICO_TRANSPORTE ]
