#Servicios
services:
    security.exception:
        class: AdminBundle\Security\ExceptionListener
        arguments: ['@admin.util', '@router']
        tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
           
    admin.user:
        class: AdminBundle\Security\UserProvider
        arguments: ['@doctrine', '@admin.util']
    
    admin.security:
        class: AdminBundle\Security\SecurityAuthentication
        arguments: ['@admin.util', '@session', '@doctrine', '@admin.user']
        
    admin.util:
        class: AdminBundle\Security\Util
        arguments: ['@router', '@session', '@cdt.logger']